[versions]
agp = "8.10.0"
composeBom = "2025.05.00"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.1.4" # Don't update for now, causes crash in release mode
keval = "1.1.1"
kotlin = "2.1.20"
ksp = "2.1.20-1.0.31"
lifecycleViewmodelCompose = "2.9.0"
roomCompiler = "2.7.1"
roomKtx = "2.7.1"
activityCompose = "1.10.1"


[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-ui = { module = "androidx.compose.ui:ui" }
keval = { module = "com.notkamui.libs:keval", version.ref = "keval" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
